# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/home/boris/Documents/Active/CSCI3430 Project/csci3430.cache/wt} [current_project]
set_property parent.project_path {/home/boris/Documents/Active/CSCI3430 Project/csci3430.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg.xci}}
set_property used_in_implementation false [get_files -all {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg.dcp}}]
set_property is_locked true [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg.xci}}]

synth_design -top game_bg -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all game_bg_
write_checkpoint -noxdef game_bg.dcp
catch { report_utilization -file game_bg_utilization_synth.rpt -pb game_bg_utilization_synth.pb }
if { [catch {
  file copy -force {/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/game_bg_synth_1/game_bg.dcp} {/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub {/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub {/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim {/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim {/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {/home/boris/Documents/Active/CSCI3430 Project/csci3430.ip_user_files/ip/game_bg}]} {
  catch { 
    file copy -force {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_stub.v}} {/home/boris/Documents/Active/CSCI3430 Project/csci3430.ip_user_files/ip/game_bg}
  }
}

if {[file isdir {/home/boris/Documents/Active/CSCI3430 Project/csci3430.ip_user_files/ip/game_bg}]} {
  catch { 
    file copy -force {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/game_bg/game_bg_stub.vhdl}} {/home/boris/Documents/Active/CSCI3430 Project/csci3430.ip_user_files/ip/game_bg}
  }
}
