# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/boris/Documents/Active/CSCI3430 Project/csci3430.cache/wt} [current_project]
set_property parent.project_path {/home/boris/Documents/Active/CSCI3430 Project/csci3430.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{/home/boris/Documents/Active/CSCI3430 Project/coegen/apple.png.coe}}
add_files {{/home/boris/Documents/Active/CSCI3430 Project/coegen/start_bg.jpeg.coe}}
add_files {{/home/boris/Documents/Active/CSCI3430 Project/coegen/game_bg.jpg.coe}}
add_files {{/home/boris/Documents/Active/CSCI3430 Project/coegen/end_bg.jpg.coe}}
add_files {{/home/boris/Documents/Active/CSCI3430 Project/coegen/snake.png.coe}}
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/video_ram_synth_1/video_ram.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/video_ram_synth_1/video_ram.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/clk_manager_synth_1/clk_manager.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/clk_manager_synth_1/clk_manager.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/start_bg_synth_1/start_bg.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/start_bg_synth_1/start_bg.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/copy_counter_synth_1/copy_counter.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/copy_counter_synth_1/copy_counter.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/game_bg_synth_1/game_bg.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/game_bg_synth_1/game_bg.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/end_bg_synth_1/end_bg.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/end_bg_synth_1/end_bg.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/apple_sprite_synth_1/apple_sprite.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/apple_sprite_synth_1/apple_sprite.dcp}}]
add_files -quiet {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/snake_sprite_synth_1/snake_sprite.dcp}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/csci3430.runs/snake_sprite_synth_1/snake_sprite.dcp}}]
read_verilog -library xil_defaultlib {
  {/home/boris/Documents/Active/CSCI3430 Project/vga_driver.v}
  {/home/boris/Documents/Active/CSCI3430 Project/gfx_engine.v}
  {/home/boris/Documents/Active/CSCI3430 Project/game.v}
}
read_xdc {{/home/boris/Documents/Active/CSCI3430 Project/zedboard_master_XDC_RevC_D_v2.xdc}}
set_property used_in_implementation false [get_files {{/home/boris/Documents/Active/CSCI3430 Project/zedboard_master_XDC_RevC_D_v2.xdc}}]

synth_design -top game -part xc7z020clg484-1
write_checkpoint -noxdef game.dcp
catch { report_utilization -file game_utilization_synth.rpt -pb game_utilization_synth.pb }
