# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/copy_counter/copy_counter.xci
# IP: The module: 'copy_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/copy_counter/copy_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'copy_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/copy_counter/copy_counter.xci
# IP: The module: 'copy_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boris/Documents/Active/CSCI3430 Project/csci3430.srcs/sources_1/ip/copy_counter/copy_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'copy_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
